### ISSUE TITLE
Unable to git clone repo on Arch

### ISSUE THREAD

**Issue by jahway603** [hinto-janai/monero-vanity#3]
Following the [Build instructions](https://github.com/hinto-janai/monero-vanity#build) fails:

```
$ git clone --recursive https://github.com/hinto-janai/monero-vanity
Cloning into 'monero-vanity'...
remote: Enumerating objects: 212, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 212 (delta 57), reused 77 (delta 32), pack-reused 100
Receiving objects: 100% (212/212), 7.11 MiB | 8.82 MiB/s, done.
Resolving deltas: 100% (90/90), done.
Submodule 'curve25519-dalek' (git@github.com:hinto-janai/curve25519-dalek.git) registered for path 'external/curve25519-dalek'
Submodule 'monero-rs' (git@github.com:hinto-janai/monero-rs.git) registered for path 'external/monero-rs'
Cloning into '/mnt/<MY-DIR>/monero-vanity/external/curve25519-dalek'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hinto-janai/curve25519-dalek.git' into submodule path '/mnt/<MY-DIR>/monero-vanity/external/curve25519-dalek' failed
Failed to clone 'external/curve25519-dalek'. Retry scheduled
Cloning into '/mnt/<MY-DIR>/monero-vanity/external/monero-rs'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hinto-janai/monero-rs.git' into submodule path '/mnt/<MY-DIR>/monero-vanity/external/monero-rs' failed
Failed to clone 'external/monero-rs'. Retry scheduled
Cloning into '/mnt/<MY-DIR>/monero-vanity/external/curve25519-dalek'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hinto-janai/curve25519-dalek.git' into submodule path '/mnt/<MY-DIR>/monero-vanity/external/curve25519-dalek' failed
Failed to clone 'external/curve25519-dalek' a second time, aborting
```

**Comment by hinto-janai** [comment]
Should be fixed by https://github.com/hinto-janai/monero-vanity/commit/91ba6b11df30e46acdc975b1e170af3995c8f731.

**Comment by jahway603** [comment]
Unfortunately that commit did not fix this for me. I was able to determine how to get it compiling on Arch Linux and wrote the [monero-vanity-git AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=monero-vanity-git) with what I learned.

**Comment by hinto-janai** [comment]
Nice, and thanks.
